# This is an example
#


steps:
  - id: helm-package
    name: gcr.io/project-virginwifi-hub/cloud-builder-helm
    args: ['package', '*']

  - id: helm-index
    name: gcr.io/project-virginwifi-hub/cloud-builder-helm
    args: ['repo', 'index', '.']
    waitFor:
      - helm-package

artifacts:
  objects:
    location: 'gs://bucket-virginwifi-hub-buildartefacts/'
    paths: ['*.tgz', 'index.yaml']
